// 🚨 CONFIGURACIÓN ÚNICA CENTRALIZADA - SINGLE SOURCE OF TRUTH (SSOT)
// Este archivo contiene TODA la información del sitio web.
// Los clientes NO técnicos solo deben editar este archivo desde GitHub.
// Todos los cambios aquí se reflejan automáticamente en todas las páginas.
// ¡NO EDITAR CÓDIGO JavaScript abajo! Solo modificar los datos aquí.

// 🎨 TEMA VISUAL - IDENTIDAD CORPORATIVA
export const THEME_CONFIG = {
  color_primario: '#039dbf',
  color_hover: '#02829e',
  color_fondo_tarjetas: '#0080ff',
}

export const WEBSITE_CONFIG = {
  numero_whatsapp: '51994942994',
  numero_whatsapp_m: '51 994 942 994',
  correo_contacto: 'info@apicperu.com',

  temporadas_carrusel: [
    {
      evento_id: 1,
      nombre_evento: 'Fiestas Patrias 2026',
      titulo_carrusel: 'Fiestas Patrias 2026',
      subtitulo_carrusel: 'Equipo audiovisual premium para celebraciones',
      imagen_carrusel: 'linear-gradient(135deg, #039dbf 0%, #0b0f19 100%)',
      imagen_url: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhGOESiDypy96M8j4gq9KdYyqGC55MoB1Wex1jhIwClalE1yYT5fpDDWKFKOGnMNyBs5aYPfUBFnMcrQFlhSx9pJn4vtrfBCFjdgGa0IOyl5owjKVcnFW_HMj0GaF8wtb_YCKYerVJQsRGn/s1600/Bandera+peruana.jpg',
      nombre_pack: 'Pack Fiestas Patrias Completo',
      descripcion_pack: 'Solución audiovisual integral para celebraciones de Fiestas Patrias con los mejores equipos de APIC.',
      equipos_incluidos: ['Domos — Combo 2', 'Foto Cabina — Combo 1', 'Plataforma 360 — Combo 2'],
    },
    {
      evento_id: 2,
      nombre_evento: 'Navidad Mágica',
      titulo_carrusel: 'Navidad Mágica',
      subtitulo_carrusel: 'Proyecciones y efectos visuales espectaculares',
      imagen_carrusel: 'linear-gradient(135deg, #0b0f19 0%, #039dbf 100%)',
      imagen_url: 'https://plus.unsplash.com/premium_photo-1661766896016-16e307246d5d?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cmVnYWxvcyUyMGRlJTIwbmF2aWRhZHxlbnwwfHwwfHx8MA%3D%3D',
      nombre_pack: 'Pack Navidad Espectacular',
      descripcion_pack: 'Vive la magia navideña con tecnología de punta. Crea experiencias inolvidables para tu familia y amigos.',
      equipos_incluidos: ['Túnel Pixel — Combo 2', 'Cabina 180 Pro — Combo 1', 'Domos — Combo 2', 'Foto Cabina — Combo 1'],
    },
    {
      evento_id: 3,
      nombre_evento: 'Eventos Corporativos',
      titulo_carrusel: 'Eventos Corporativos',
      subtitulo_carrusel: 'Soluciones profesionales para tu empresa',
      imagen_carrusel: 'linear-gradient(135deg, #039dbf 0%, #111827 100%)',
      imagen_url: 'https://www.epgdlaw.com/wp-content/uploads/2015/10/89273783_l.jpg',
      nombre_pack: 'Pack Corporativo Premium',
      descripcion_pack: 'Eleva el nivel de tus eventos empresariales con soluciones audiovisuales de clase mundial.',
      equipos_incluidos: ['Plataforma 360 — Combo 2', 'Aéreo 360', 'Foto Cabina — Combo 1'],
    },
    {
      evento_id: 4,
      nombre_evento: 'Eventos de Verano',
      titulo_carrusel: 'Eventos de Verano',
      subtitulo_carrusel: 'Soluciones profesionales para tu empresa',
      imagen_carrusel: 'linear-gradient(135deg, #039dbf 0%, #111827 100%)',
      imagen_url: 'https://plus.unsplash.com/premium_photo-1663045661039-32a3b7e93ad3?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c29sJTIwZGUlMjB2ZXJhbm98ZW58MHx8MHx8fDA%3D',
      nombre_pack: 'Pack Veraniego Completo',
      descripcion_pack: 'Eleva el nivel de tus eventos empresariales con soluciones audiovisuales de clase mundial.',
      equipos_incluidos: ['Foto Cabina — Combo 1', 'Cabina Espejada — Combo 1', 'Cabina 180 Pro — Combo 1', 'Aéreo 360'],
    },
  ],

  // 🗂️ SECCIONES DE CATÁLOGO — ARQUITECTURA POR FAMILIA MADRE
  // Cada bloque de 'secciones_catalogo' representa UNA familia de producto
  // (p. ej. 'Plataforma 360', 'Domos'). Dentro de cada familia, cada nivel
  // Combo N es su PROPIO objeto de producto independiente (id, sku, imagen,
  // descripción, ficha técnica y garantías propias). El Mega Menu y el Home
  // recorren este arreglo dinámicamente: agregar una nueva familia aquí
  // basta para que aparezca automáticamente en ambos.
  secciones_catalogo: [
    {
      id_seccion: 'plataforma-360',
      titulo_seccion: 'Plataforma 360',
      productos: [
        {
          id: 1,
          nombre: 'Plataforma 360 — Combo 1',
          sku: 'P360-EVT-001-C1',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular',
            'Costo: 2200 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 1. Peso: 25 kg. Costo: 2200 soles.',
          descripcion_larga: 'Plataforma 360 — Combo 1. Especificaciones: Peso: 25 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular. Costo de este nivel: 2200 soles.',
          imagenes_galeria: ['/imagenes/plataforma-360-combo-1-1.jpg', '/imagenes/plataforma-360-combo-1-2.jpg', '/imagenes/plataforma-360-combo-1-3.jpg', '/imagenes/plataforma-360-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular' },
            { label: 'Costo', valor: '2200 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 2,
          nombre: 'Plataforma 360 — Combo 2',
          sku: 'P360-EVT-001-C2',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado',
            'Costo: 2300 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 2. Peso: 25 kg. Costo: 2300 soles.',
          descripcion_larga: 'Plataforma 360 — Combo 2. Especificaciones: Peso: 25 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado. Costo de este nivel: 2300 soles.',
          imagenes_galeria: ['/imagenes/plataforma-360-combo-2-1.jpg', '/imagenes/plataforma-360-combo-2-2.jpg', '/imagenes/plataforma-360-combo-2-3.jpg', '/imagenes/plataforma-360-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado' },
            { label: 'Costo', valor: '2300 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 3,
          nombre: 'Plataforma 360 — Combo 3',
          sku: 'P360-EVT-001-C3',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras',
            'Costo: 2500 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 3. Peso: 25 kg. Costo: 2500 soles.',
          descripcion_larga: 'Plataforma 360 — Combo 3. Especificaciones: Peso: 25 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras. Costo de este nivel: 2500 soles.',
          imagenes_galeria: ['/imagenes/plataforma-360-combo-3-1.jpg', '/imagenes/plataforma-360-combo-3-2.jpg', '/imagenes/plataforma-360-combo-3-3.jpg', '/imagenes/plataforma-360-combo-3-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras' },
            { label: 'Costo', valor: '2500 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 4,
          nombre: 'Plataforma 360 — Combo 4',
          sku: 'P360-EVT-001-C4',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja',
            'Costo: 3100 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 4. Peso: 25 kg. Costo: 3100 soles.',
          descripcion_larga: 'Plataforma 360 — Combo 4. Especificaciones: Peso: 25 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja. Costo de este nivel: 3100 soles.',
          imagenes_galeria: ['/imagenes/plataforma-360-combo-4-1.jpg', '/imagenes/plataforma-360-combo-4-2.jpg', '/imagenes/plataforma-360-combo-4-3.jpg', '/imagenes/plataforma-360-combo-4-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja' },
            { label: 'Costo', valor: '3100 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 5,
          nombre: 'Plataforma 360 — Combo 5',
          sku: 'P360-EVT-001-C5',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja, estuche de lona acolchado de 1 mt, carrito de fierro con 4 ruedas para transportar la plataforma, power bank',
            'Costo: 3600 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 5. Peso: 25 kg. Costo: 3600 soles.',
          descripcion_larga: 'Plataforma 360 — Combo 5. Especificaciones: Peso: 25 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja, estuche de lona acolchado de 1 mt, carrito de fierro con 4 ruedas para transportar la plataforma, power bank. Costo de este nivel: 3600 soles.',
          imagenes_galeria: ['/imagenes/plataforma-360-combo-5-1.jpg', '/imagenes/plataforma-360-combo-5-2.jpg', '/imagenes/plataforma-360-combo-5-3.jpg', '/imagenes/plataforma-360-combo-5-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja, estuche de lona acolchado de 1 mt, carrito de fierro con 4 ruedas para transportar la plataforma, power bank' },
            { label: 'Costo', valor: '3600 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'plataforma-infinito',
      titulo_seccion: 'Plataforma Infinito',
      productos: [
        {
          id: 6,
          nombre: 'Plataforma Infinito — Combo 1',
          sku: 'PINF-EVT-002-C1',
          categoria: 'Plataforma Infinito',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido',
            'Costo: 3050 soles',
          ],
          descripcion: 'Plataforma Infinito — Combo 1. Peso: 35 kg. Costo: 3050 soles.',
          descripcion_larga: 'Plataforma Infinito — Combo 1. Especificaciones: Peso: 35 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Vidrio: Templado de 10mm, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido. Costo de este nivel: 3050 soles.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-combo-1-1.jpg', '/imagenes/plataforma-infinito-combo-1-2.jpg', '/imagenes/plataforma-infinito-combo-1-3.jpg', '/imagenes/plataforma-infinito-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido' },
            { label: 'Costo', valor: '3050 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 7,
          nombre: 'Plataforma Infinito — Combo 2',
          sku: 'PINF-EVT-002-C2',
          categoria: 'Plataforma Infinito',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación',
            'Costo: 3450 soles',
          ],
          descripcion: 'Plataforma Infinito — Combo 2. Peso: 35 kg. Costo: 3450 soles.',
          descripcion_larga: 'Plataforma Infinito — Combo 2. Especificaciones: Peso: 35 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Vidrio: Templado de 10mm, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación. Costo de este nivel: 3450 soles.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-combo-2-1.jpg', '/imagenes/plataforma-infinito-combo-2-2.jpg', '/imagenes/plataforma-infinito-combo-2-3.jpg', '/imagenes/plataforma-infinito-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación' },
            { label: 'Costo', valor: '3450 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 8,
          nombre: 'Plataforma Infinito — Combo 3',
          sku: 'PINF-EVT-002-C3',
          categoria: 'Plataforma Infinito',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación, máquina de humo, máquina de burbuja',
            'Costo: 3750 soles',
          ],
          descripcion: 'Plataforma Infinito — Combo 3. Peso: 35 kg. Costo: 3750 soles.',
          descripcion_larga: 'Plataforma Infinito — Combo 3. Especificaciones: Peso: 35 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Vidrio: Templado de 10mm, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación, máquina de humo, máquina de burbuja. Costo de este nivel: 3750 soles.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-combo-3-1.jpg', '/imagenes/plataforma-infinito-combo-3-2.jpg', '/imagenes/plataforma-infinito-combo-3-3.jpg', '/imagenes/plataforma-infinito-combo-3-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación, máquina de humo, máquina de burbuja' },
            { label: 'Costo', valor: '3750 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'plataforma-infinito-holograma',
      titulo_seccion: 'Plataforma Infinito Holograma',
      productos: [
        {
          id: 9,
          nombre: 'Plataforma Infinito Holograma — Combo 1',
          sku: 'PINFH-EVT-003-C1',
          categoria: 'Plataforma Infinito Holograma',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido',
            'Costo: 3600 soles',
          ],
          descripcion: 'Plataforma Infinito Holograma — Combo 1. Peso: 35 kg. Costo: 3600 soles.',
          descripcion_larga: 'Plataforma Infinito Holograma — Combo 1. Especificaciones: Peso: 35 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Vidrio: Templado de 10mm, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido. Costo de este nivel: 3600 soles.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-holograma-combo-1-1.jpg', '/imagenes/plataforma-infinito-holograma-combo-1-2.jpg', '/imagenes/plataforma-infinito-holograma-combo-1-3.jpg', '/imagenes/plataforma-infinito-holograma-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido' },
            { label: 'Costo', valor: '3600 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 10,
          nombre: 'Plataforma Infinito Holograma — Combo 2',
          sku: 'PINFH-EVT-003-C2',
          categoria: 'Plataforma Infinito Holograma',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación',
            'Costo: 4000 soles',
          ],
          descripcion: 'Plataforma Infinito Holograma — Combo 2. Peso: 35 kg. Costo: 4000 soles.',
          descripcion_larga: 'Plataforma Infinito Holograma — Combo 2. Especificaciones: Peso: 35 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Vidrio: Templado de 10mm, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación. Costo de este nivel: 4000 soles.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-holograma-combo-2-1.jpg', '/imagenes/plataforma-infinito-holograma-combo-2-2.jpg', '/imagenes/plataforma-infinito-holograma-combo-2-3.jpg', '/imagenes/plataforma-infinito-holograma-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación' },
            { label: 'Costo', valor: '4000 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 11,
          nombre: 'Plataforma Infinito Holograma — Combo 3',
          sku: 'PINFH-EVT-003-C3',
          categoria: 'Plataforma Infinito Holograma',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación, máquina de humo, máquina de burbuja',
            'Costo: 4300 soles',
          ],
          descripcion: 'Plataforma Infinito Holograma — Combo 3. Peso: 35 kg. Costo: 4300 soles.',
          descripcion_larga: 'Plataforma Infinito Holograma — Combo 3. Especificaciones: Peso: 35 kg, Medida: 1 metro de diámetro, Capacidad: 4-5 personas, Color: Negro, Garantía: 1 año, Material: Metal, Vidrio: Templado de 10mm, Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación, máquina de humo, máquina de burbuja. Costo de este nivel: 4300 soles.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-holograma-combo-3-1.jpg', '/imagenes/plataforma-infinito-holograma-combo-3-2.jpg', '/imagenes/plataforma-infinito-holograma-combo-3-3.jpg', '/imagenes/plataforma-infinito-holograma-combo-3-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación, máquina de humo, máquina de burbuja' },
            { label: 'Costo', valor: '4300 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'glass-booth',
      titulo_seccion: 'Glass Booth',
      productos: [
        {
          id: 12,
          nombre: 'Glass Booth',
          sku: 'GBTH-EVT-004',
          categoria: 'Glass Booth',
          especificaciones: [
            'Estructura: Desarmable, cuadrada, de 1.22 x 1.22 mt',
            'Altura: 2 metros',
            'Plancha: Negra para branding',
            'Barras: Blancas para iluminación',
            'Forro: Tela negra',
            'Mica: Transparente de 60cm x 1.22cm, efecto espejo de 3mm de espesor',
            'Costo: 1500 soles',
          ],
          descripcion: 'Glass Booth. Estructura: desarmable, cuadrada, de 1.22 x 1.22 mt. Costo: 1500 soles.',
          descripcion_larga: 'Glass Booth. Especificaciones: Estructura: Desarmable, cuadrada, de 1.22 x 1.22 mt, Altura: 2 metros, Plancha: Negra para branding, Barras: Blancas para iluminación, Forro: Tela negra, Mica: Transparente de 60cm x 1.22cm, efecto espejo de 3mm de espesor. Costo de este nivel: 1500 soles.',
          imagenes_galeria: ['/imagenes/glass-booth-1.jpg', '/imagenes/glass-booth-2.jpg', '/imagenes/glass-booth-3.jpg', '/imagenes/glass-booth-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Desarmable, cuadrada, de 1.22 x 1.22 mt' },
            { label: 'Altura', valor: '2 metros' },
            { label: 'Plancha', valor: 'Negra para branding' },
            { label: 'Barras', valor: 'Blancas para iluminación' },
            { label: 'Forro', valor: 'Tela negra' },
            { label: 'Mica', valor: 'Transparente de 60cm x 1.22cm, efecto espejo de 3mm de espesor' },
            { label: 'Costo', valor: '1500 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'tunel-pixel',
      titulo_seccion: 'Túnel Pixel',
      productos: [
        {
          id: 13,
          nombre: 'Túnel Pixel — Combo 1',
          sku: 'TPIX-EVT-005-C1',
          categoria: 'Túnel Pixel',
          especificaciones: [
            'Estructura: Completamente desarmable',
            'Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad',
            'Material: Acero cuadrado',
            'Color: Negro',
            'Arcos: 6 arcos hexagonales',
            'Costo: 950 soles',
          ],
          descripcion: 'Túnel Pixel — Combo 1. Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad. Costo: 950 soles.',
          descripcion_larga: 'Túnel Pixel — Combo 1. Especificaciones: Estructura: Completamente desarmable, Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad, Material: Acero cuadrado, Color: Negro, Arcos: 6 arcos hexagonales. Costo de este nivel: 950 soles.',
          imagenes_galeria: ['/imagenes/tunel-pixel-combo-1-1.jpg', '/imagenes/tunel-pixel-combo-1-2.jpg', '/imagenes/tunel-pixel-combo-1-3.jpg', '/imagenes/tunel-pixel-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Completamente desarmable' },
            { label: 'Medidas', valor: '2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad' },
            { label: 'Material', valor: 'Acero cuadrado' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Arcos', valor: '6 arcos hexagonales' },
            { label: 'Costo', valor: '950 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 14,
          nombre: 'Túnel Pixel — Combo 2',
          sku: 'TPIX-EVT-005-C2',
          categoria: 'Túnel Pixel',
          especificaciones: [
            'Estructura: Completamente desarmable',
            'Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad',
            'Material: Acero cuadrado',
            'Color: Negro',
            'Arcos: 6 arcos hexagonales',
            'Iluminación: 30 barras pixel con enchufe en cada arco',
            'Costo: 2250 soles',
          ],
          descripcion: 'Túnel Pixel — Combo 2. Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad. Costo: 2250 soles.',
          descripcion_larga: 'Túnel Pixel — Combo 2. Especificaciones: Estructura: Completamente desarmable, Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad, Material: Acero cuadrado, Color: Negro, Arcos: 6 arcos hexagonales, Iluminación: 30 barras pixel con enchufe en cada arco. Costo de este nivel: 2250 soles.',
          imagenes_galeria: ['/imagenes/tunel-pixel-combo-2-1.jpg', '/imagenes/tunel-pixel-combo-2-2.jpg', '/imagenes/tunel-pixel-combo-2-3.jpg', '/imagenes/tunel-pixel-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Completamente desarmable' },
            { label: 'Medidas', valor: '2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad' },
            { label: 'Material', valor: 'Acero cuadrado' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Arcos', valor: '6 arcos hexagonales' },
            { label: 'Iluminación', valor: '30 barras pixel con enchufe en cada arco' },
            { label: 'Costo', valor: '2250 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 15,
          nombre: 'Túnel Pixel — Combo 3',
          sku: 'TPIX-EVT-005-C3',
          categoria: 'Túnel Pixel',
          especificaciones: [
            'Estructura: Completamente desarmable',
            'Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad',
            'Material: Acero cuadrado',
            'Color: Negro',
            'Arcos: 6 arcos hexagonales',
            'Iluminación: 30 barras pixel',
            'Transformadores: 6 transformadores de 12v',
            'Cableado: 5 cables de empalme',
            'Control: 1 controlador rítmico, controlable por app',
            'Costo: 2650 soles',
          ],
          descripcion: 'Túnel Pixel — Combo 3. Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad. Costo: 2650 soles.',
          descripcion_larga: 'Túnel Pixel — Combo 3. Especificaciones: Estructura: Completamente desarmable, Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad, Material: Acero cuadrado, Color: Negro, Arcos: 6 arcos hexagonales, Iluminación: 30 barras pixel, Transformadores: 6 transformadores de 12v, Cableado: 5 cables de empalme, Control: 1 controlador rítmico, controlable por app. Costo de este nivel: 2650 soles.',
          imagenes_galeria: ['/imagenes/tunel-pixel-combo-3-1.jpg', '/imagenes/tunel-pixel-combo-3-2.jpg', '/imagenes/tunel-pixel-combo-3-3.jpg', '/imagenes/tunel-pixel-combo-3-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Completamente desarmable' },
            { label: 'Medidas', valor: '2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad' },
            { label: 'Material', valor: 'Acero cuadrado' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Arcos', valor: '6 arcos hexagonales' },
            { label: 'Iluminación', valor: '30 barras pixel' },
            { label: 'Transformadores', valor: '6 transformadores de 12v' },
            { label: 'Cableado', valor: '5 cables de empalme' },
            { label: 'Control', valor: '1 controlador rítmico, controlable por app' },
            { label: 'Costo', valor: '2650 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'domos',
      titulo_seccion: 'Domos',
      productos: [
        {
          id: 16,
          nombre: 'Domos — Combo 1',
          sku: 'DOMO-EVT-006-C1',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Básico',
            'Medida armado: 2.25 mt alto x 3.40 mt ancho',
            'Iluminación: 35 barras LED blancas',
            'Piezas: 16 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Precio: 2350 soles',
          ],
          descripcion: 'Domos — Combo 1. Medida armado: 2.25 mt alto x 3.40 mt ancho. Precio: 2350 soles.',
          descripcion_larga: 'Domos — Combo 1. Especificaciones: Variante: Domo Básico, Medida armado: 2.25 mt alto x 3.40 mt ancho, Iluminación: 35 barras LED blancas, Piezas: 16 piezas, Cableado: Incluido con empalmes, Material: Metal, fierro, tubo cuadrado. Precio de este nivel: 2350 soles.',
          imagenes_galeria: ['/imagenes/domos-combo-1-1.jpg', '/imagenes/domos-combo-1-2.jpg', '/imagenes/domos-combo-1-3.jpg', '/imagenes/domos-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Básico' },
            { label: 'Medida armado', valor: '2.25 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '35 barras LED blancas' },
            { label: 'Piezas', valor: '16 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Precio', valor: '2350 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 17,
          nombre: 'Domos — Combo 2',
          sku: 'DOMO-EVT-006-C2',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Premium',
            'Medida armado: 3 mt alto x 3.40 mt ancho',
            'Iluminación: 65 barras LED blancas',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Precio: 3150 soles',
          ],
          descripcion: 'Domos — Combo 2. Medida armado: 3 mt alto x 3.40 mt ancho. Precio: 3150 soles.',
          descripcion_larga: 'Domos — Combo 2. Especificaciones: Variante: Domo Premium, Medida armado: 3 mt alto x 3.40 mt ancho, Iluminación: 65 barras LED blancas, Piezas: 21 piezas, Cableado: Incluido con empalmes, Material: Metal, fierro, tubo cuadrado. Precio de este nivel: 3150 soles.',
          imagenes_galeria: ['/imagenes/domos-combo-2-1.jpg', '/imagenes/domos-combo-2-2.jpg', '/imagenes/domos-combo-2-3.jpg', '/imagenes/domos-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Premium' },
            { label: 'Medida armado', valor: '3 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '65 barras LED blancas' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Precio', valor: '3150 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 18,
          nombre: 'Domos — Combo 3',
          sku: 'DOMO-EVT-006-C3',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Premium Pixel',
            'Medida armado: 3 mt alto x 3.40 mt ancho',
            'Iluminación: 65 barras LED blancas + 51 barras pixel',
            'Control: 1 controlador',
            'Transformadores: 5 transformadores de 12v',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Precio: 5199 soles',
          ],
          descripcion: 'Domos — Combo 3. Medida armado: 3 mt alto x 3.40 mt ancho. Precio: 5199 soles.',
          descripcion_larga: 'Domos — Combo 3. Especificaciones: Variante: Domo Premium Pixel, Medida armado: 3 mt alto x 3.40 mt ancho, Iluminación: 65 barras LED blancas + 51 barras pixel, Control: 1 controlador, Transformadores: 5 transformadores de 12v, Piezas: 21 piezas, Cableado: Incluido con empalmes, Material: Metal, fierro, tubo cuadrado. Precio de este nivel: 5199 soles.',
          imagenes_galeria: ['/imagenes/domos-combo-3-1.jpg', '/imagenes/domos-combo-3-2.jpg', '/imagenes/domos-combo-3-3.jpg', '/imagenes/domos-combo-3-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Premium Pixel' },
            { label: 'Medida armado', valor: '3 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '65 barras LED blancas + 51 barras pixel' },
            { label: 'Control', valor: '1 controlador' },
            { label: 'Transformadores', valor: '5 transformadores de 12v' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Precio', valor: '5199 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 19,
          nombre: 'Domos — Combo 4',
          sku: 'DOMO-EVT-006-C4',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Aéreo',
            'Medida armado: 3 mt alto x 3.40 mt ancho',
            'Iluminación: 65 barras LED blancas',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Brazo: Extendible',
            'Control: Caja de control de velocidad, inalámbrico',
            'Transformador: 20v',
            'Cable: 6 mts',
            'Soporte: Para celular',
            'Precio: 4350 soles',
          ],
          descripcion: 'Domos — Combo 4. Medida armado: 3 mt alto x 3.40 mt ancho. Precio: 4350 soles.',
          descripcion_larga: 'Domos — Combo 4. Especificaciones: Variante: Domo Aéreo, Medida armado: 3 mt alto x 3.40 mt ancho, Iluminación: 65 barras LED blancas, Piezas: 21 piezas, Cableado: Incluido con empalmes, Material: Metal, fierro, tubo cuadrado, Brazo: Extendible, Control: Caja de control de velocidad, inalámbrico, Transformador: 20v, Cable: 6 mts, Soporte: Para celular. Precio de este nivel: 4350 soles.',
          imagenes_galeria: ['/imagenes/domos-combo-4-1.jpg', '/imagenes/domos-combo-4-2.jpg', '/imagenes/domos-combo-4-3.jpg', '/imagenes/domos-combo-4-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Aéreo' },
            { label: 'Medida armado', valor: '3 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '65 barras LED blancas' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Brazo', valor: 'Extendible' },
            { label: 'Control', valor: 'Caja de control de velocidad, inalámbrico' },
            { label: 'Transformador', valor: '20v' },
            { label: 'Cable', valor: '6 mts' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Precio', valor: '4350 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 20,
          nombre: 'Domos — Combo 5',
          sku: 'DOMO-EVT-006-C5',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Aéreo Premium Pixel',
            'Iluminación: 65 barras LED blancas + 51 barras pixel',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Brazo: Extendible',
            'Control: Caja de control de velocidad, inalámbrico, 1 controlador para pixel',
            'Transformadores: 20v (brazo) + 5 transformadores de 12v (pixel)',
            'Cable: RCA de 6 mts',
            'Soporte: Para celular',
            'Precio: 6550 soles',
          ],
          descripcion: 'Domos — Combo 5. Precio: 6550 soles.',
          descripcion_larga: 'Domos — Combo 5. Especificaciones: Variante: Domo Aéreo Premium Pixel, Iluminación: 65 barras LED blancas + 51 barras pixel, Piezas: 21 piezas, Cableado: Incluido con empalmes, Material: Metal, fierro, tubo cuadrado, Brazo: Extendible, Control: Caja de control de velocidad, inalámbrico, 1 controlador para pixel, Transformadores: 20v (brazo) + 5 transformadores de 12v (pixel), Cable: RCA de 6 mts, Soporte: Para celular. Precio de este nivel: 6550 soles.',
          imagenes_galeria: ['/imagenes/domos-combo-5-1.jpg', '/imagenes/domos-combo-5-2.jpg', '/imagenes/domos-combo-5-3.jpg', '/imagenes/domos-combo-5-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Aéreo Premium Pixel' },
            { label: 'Iluminación', valor: '65 barras LED blancas + 51 barras pixel' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Brazo', valor: 'Extendible' },
            { label: 'Control', valor: 'Caja de control de velocidad, inalámbrico, 1 controlador para pixel' },
            { label: 'Transformadores', valor: '20v (brazo) + 5 transformadores de 12v (pixel)' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Precio', valor: '6550 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'foto-cabina',
      titulo_seccion: 'Foto Cabina',
      productos: [
        {
          id: 21,
          nombre: 'Foto Cabina — Combo 1',
          sku: 'FCAB-EVT-007-C1',
          categoria: 'Foto Cabina',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad',
            'Mesa: Para impresora, 40x40 cm',
            'Tambor: 45 cm',
            'Aro LED: 45 cm',
            'Controles: 1 control para LED RGB, 1 control para el aro LED',
            'Transformadores: 2 transformadores de 12v',
            'Vinil: Personalizado — foto cabina, mesa y tambor',
            'Soporte: Para iPad',
            'Costo: 2100 soles',
          ],
          descripcion: 'Foto Cabina — Combo 1. Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad. Costo: 2100 soles.',
          descripcion_larga: 'Foto Cabina — Combo 1. Especificaciones: Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad, Mesa: Para impresora, 40x40 cm, Tambor: 45 cm, Aro LED: 45 cm, Controles: 1 control para LED RGB, 1 control para el aro LED, Transformadores: 2 transformadores de 12v, Vinil: Personalizado — foto cabina, mesa y tambor, Soporte: Para iPad. Costo de este nivel: 2100 soles.',
          imagenes_galeria: ['/imagenes/foto-cabina-combo-1-1.jpg', '/imagenes/foto-cabina-combo-1-2.jpg', '/imagenes/foto-cabina-combo-1-3.jpg', '/imagenes/foto-cabina-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho x 15 cm profundidad' },
            { label: 'Mesa', valor: 'Para impresora, 40x40 cm' },
            { label: 'Tambor', valor: '45 cm' },
            { label: 'Aro LED', valor: '45 cm' },
            { label: 'Controles', valor: '1 control para LED RGB, 1 control para el aro LED' },
            { label: 'Transformadores', valor: '2 transformadores de 12v' },
            { label: 'Vinil', valor: 'Personalizado — foto cabina, mesa y tambor' },
            { label: 'Soporte', valor: 'Para iPad' },
            { label: 'Costo', valor: '2100 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 22,
          nombre: 'Foto Cabina — Combo 2',
          sku: 'FCAB-EVT-007-C2',
          categoria: 'Foto Cabina',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad',
            'Mesa: Para impresora, 40x40 cm',
            'Tambor: 45 cm',
            'Aro LED: 45 cm',
            'Controles: 1 control para LED RGB, 1 control para el aro LED',
            'Transformadores: 2 transformadores de 12v',
            'Vinil: Personalizado — foto cabina, mesa y tambor',
            'Soporte: Para iPad',
            'Accesorios adicionales: Guillotina incluida',
            'Impresora: Epson L1250 WiFi',
            'Costo: 3500 soles',
          ],
          descripcion: 'Foto Cabina — Combo 2. Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad. Costo: 3500 soles.',
          descripcion_larga: 'Foto Cabina — Combo 2. Especificaciones: Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad, Mesa: Para impresora, 40x40 cm, Tambor: 45 cm, Aro LED: 45 cm, Controles: 1 control para LED RGB, 1 control para el aro LED, Transformadores: 2 transformadores de 12v, Vinil: Personalizado — foto cabina, mesa y tambor, Soporte: Para iPad, Accesorios adicionales: Guillotina incluida, Impresora: Epson L1250 WiFi. Costo de este nivel: 3500 soles.',
          imagenes_galeria: ['/imagenes/foto-cabina-combo-2-1.jpg', '/imagenes/foto-cabina-combo-2-2.jpg', '/imagenes/foto-cabina-combo-2-3.jpg', '/imagenes/foto-cabina-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho x 15 cm profundidad' },
            { label: 'Mesa', valor: 'Para impresora, 40x40 cm' },
            { label: 'Tambor', valor: '45 cm' },
            { label: 'Aro LED', valor: '45 cm' },
            { label: 'Controles', valor: '1 control para LED RGB, 1 control para el aro LED' },
            { label: 'Transformadores', valor: '2 transformadores de 12v' },
            { label: 'Vinil', valor: 'Personalizado — foto cabina, mesa y tambor' },
            { label: 'Soporte', valor: 'Para iPad' },
            { label: 'Accesorios adicionales', valor: 'Guillotina incluida' },
            { label: 'Impresora', valor: 'Epson L1250 WiFi' },
            { label: 'Costo', valor: '3500 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'aereo-360',
      titulo_seccion: 'Aéreo 360',
      productos: [
        {
          id: 23,
          nombre: 'Aéreo 360',
          sku: 'A360-EVT-008',
          categoria: 'Aéreo 360',
          especificaciones: [
            'Estructura: Desarmable en 6 piezas',
            'Medidas: 2.40 mt alto x 3 mts ancho',
            'Forro: Color negro',
            'Brazo: Regulable',
            'Control: Caja de control de velocidad, inalámbrico',
            'Transformador: 20v',
            'Soporte: Para celular',
            'Costo: 3200 soles',
          ],
          descripcion: 'Aéreo 360. Medidas: 2.40 mt alto x 3 mts ancho. Costo: 3200 soles.',
          descripcion_larga: 'Aéreo 360. Especificaciones: Estructura: Desarmable en 6 piezas, Medidas: 2.40 mt alto x 3 mts ancho, Forro: Color negro, Brazo: Regulable, Control: Caja de control de velocidad, inalámbrico, Transformador: 20v, Soporte: Para celular. Costo de este nivel: 3200 soles.',
          imagenes_galeria: ['/imagenes/aereo-360-1.jpg', '/imagenes/aereo-360-2.jpg', '/imagenes/aereo-360-3.jpg', '/imagenes/aereo-360-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Desarmable en 6 piezas' },
            { label: 'Medidas', valor: '2.40 mt alto x 3 mts ancho' },
            { label: 'Forro', valor: 'Color negro' },
            { label: 'Brazo', valor: 'Regulable' },
            { label: 'Control', valor: 'Caja de control de velocidad, inalámbrico' },
            { label: 'Transformador', valor: '20v' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Costo', valor: '3200 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'balaustres',
      titulo_seccion: 'Balaustres',
      productos: [
        {
          id: 24,
          nombre: 'Balaustres',
          sku: 'BALU-EVT-009',
          categoria: 'Balaustres',
          especificaciones: [
            'Balaustre: Color dorado, 1 mt',
            'Cordón: Color rojo, 1.50 mts',
            'Disco: De pesa, para base',
            'Estructura: Desarmable, 6 piezas',
            'Costo: 210 soles',
          ],
          descripcion: 'Balaustres. Estructura: desarmable, 6 piezas. Costo: 210 soles.',
          descripcion_larga: 'Balaustres. Especificaciones: Balaustre: Color dorado, 1 mt, Cordón: Color rojo, 1.50 mts, Disco: De pesa, para base, Estructura: Desarmable, 6 piezas. Costo de este nivel: 210 soles.',
          imagenes_galeria: ['/imagenes/balaustres-1.jpg', '/imagenes/balaustres-2.jpg', '/imagenes/balaustres-3.jpg', '/imagenes/balaustres-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Balaustre', valor: 'Color dorado, 1 mt' },
            { label: 'Cordón', valor: 'Color rojo, 1.50 mts' },
            { label: 'Disco', valor: 'De pesa, para base' },
            { label: 'Estructura', valor: 'Desarmable, 6 piezas' },
            { label: 'Costo', valor: '210 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'cabina-espejada',
      titulo_seccion: 'Cabina Espejada',
      productos: [
        {
          id: 25,
          nombre: 'Cabina Espejada — Combo 1',
          sku: 'CESP-EVT-010-C1',
          categoria: 'Cabina Espejada',
          especificaciones: [
            'Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad',
            'Material: Tubo cuadrado, acero y fierro',
            'Color: Negro',
            'Costo: 650 soles',
          ],
          descripcion: 'Cabina Espejada — Combo 1. Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad. Costo: 650 soles.',
          descripcion_larga: 'Cabina Espejada — Combo 1. Especificaciones: Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad, Material: Tubo cuadrado, acero y fierro, Color: Negro. Costo de este nivel: 650 soles.',
          imagenes_galeria: ['/imagenes/cabina-espejada-combo-1-1.jpg', '/imagenes/cabina-espejada-combo-1-2.jpg', '/imagenes/cabina-espejada-combo-1-3.jpg', '/imagenes/cabina-espejada-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Medidas', valor: '2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad' },
            { label: 'Material', valor: 'Tubo cuadrado, acero y fierro' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Costo', valor: '650 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 26,
          nombre: 'Cabina Espejada — Combo 2',
          sku: 'CESP-EVT-010-C2',
          categoria: 'Cabina Espejada',
          especificaciones: [
            'Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad',
            'Material: Tubo cuadrado, acero y fierro',
            'Color: Negro',
            'Acabado: 6 planchas tipo espejo plateado de 8mm de espesor',
            'Ensamblaje: Con pernos',
            'Precio: 2250 soles',
          ],
          descripcion: 'Cabina Espejada — Combo 2. Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad. Precio: 2250 soles.',
          descripcion_larga: 'Cabina Espejada — Combo 2. Especificaciones: Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad, Material: Tubo cuadrado, acero y fierro, Color: Negro, Acabado: 6 planchas tipo espejo plateado de 8mm de espesor, Ensamblaje: Con pernos. Precio de este nivel: 2250 soles.',
          imagenes_galeria: ['/imagenes/cabina-espejada-combo-2-1.jpg', '/imagenes/cabina-espejada-combo-2-2.jpg', '/imagenes/cabina-espejada-combo-2-3.jpg', '/imagenes/cabina-espejada-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Medidas', valor: '2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad' },
            { label: 'Material', valor: 'Tubo cuadrado, acero y fierro' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Acabado', valor: '6 planchas tipo espejo plateado de 8mm de espesor' },
            { label: 'Ensamblaje', valor: 'Con pernos' },
            { label: 'Precio', valor: '2250 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
    {
      id_seccion: 'cabina-180-pro',
      titulo_seccion: 'Cabina 180 Pro',
      productos: [
        {
          id: 27,
          nombre: 'Cabina 180 Pro — Combo 1',
          sku: 'C180-EVT-011-C1',
          categoria: 'Cabina 180 Pro',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho',
            'Brazo: 2.40 mts alto',
            'Soporte: Para celular',
            'Transformador: 12v',
            'Control: Caja de control de velocidad',
            'Mando: Joystick',
            'Cable: RCA de 6 mts',
            'Costo: 2900 soles',
          ],
          descripcion: 'Cabina 180 Pro — Combo 1. Estructura: 1.20 mt alto x 30 cm ancho. Costo: 2900 soles.',
          descripcion_larga: 'Cabina 180 Pro — Combo 1. Especificaciones: Estructura: 1.20 mt alto x 30 cm ancho, Brazo: 2.40 mts alto, Soporte: Para celular, Transformador: 12v, Control: Caja de control de velocidad, Mando: Joystick, Cable: RCA de 6 mts. Costo de este nivel: 2900 soles.',
          imagenes_galeria: ['/imagenes/cabina-180-pro-combo-1-1.jpg', '/imagenes/cabina-180-pro-combo-1-2.jpg', '/imagenes/cabina-180-pro-combo-1-3.jpg', '/imagenes/cabina-180-pro-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho' },
            { label: 'Brazo', valor: '2.40 mts alto' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Transformador', valor: '12v' },
            { label: 'Control', valor: 'Caja de control de velocidad' },
            { label: 'Mando', valor: 'Joystick' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Costo', valor: '2900 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 28,
          nombre: 'Cabina 180 Pro — Combo 2',
          sku: 'C180-EVT-011-C2',
          categoria: 'Cabina 180 Pro',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho',
            'Brazo: 2.40 mts alto',
            'Soporte: Para celular',
            'Transformador: 12v',
            'Control: Caja de control de velocidad',
            'Mando: Joystick',
            'Cable: RCA de 6 mts',
            'Iluminación: LED decorativo en la estructura',
            'Personalización: Brandeado en la estructura',
            'Costo: 3050 soles',
          ],
          descripcion: 'Cabina 180 Pro — Combo 2. Estructura: 1.20 mt alto x 30 cm ancho. Costo: 3050 soles.',
          descripcion_larga: 'Cabina 180 Pro — Combo 2. Especificaciones: Estructura: 1.20 mt alto x 30 cm ancho, Brazo: 2.40 mts alto, Soporte: Para celular, Transformador: 12v, Control: Caja de control de velocidad, Mando: Joystick, Cable: RCA de 6 mts, Iluminación: LED decorativo en la estructura, Personalización: Brandeado en la estructura. Costo de este nivel: 3050 soles.',
          imagenes_galeria: ['/imagenes/cabina-180-pro-combo-2-1.jpg', '/imagenes/cabina-180-pro-combo-2-2.jpg', '/imagenes/cabina-180-pro-combo-2-3.jpg', '/imagenes/cabina-180-pro-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho' },
            { label: 'Brazo', valor: '2.40 mts alto' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Transformador', valor: '12v' },
            { label: 'Control', valor: 'Caja de control de velocidad' },
            { label: 'Mando', valor: 'Joystick' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Iluminación', valor: 'LED decorativo en la estructura' },
            { label: 'Personalización', valor: 'Brandeado en la estructura' },
            { label: 'Costo', valor: '3050 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
        {
          id: 29,
          nombre: 'Cabina 180 Pro — Combo 3',
          sku: 'C180-EVT-011-C3',
          categoria: 'Cabina 180 Pro',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho',
            'Brazo: 2.40 mts alto',
            'Soporte: Para celular',
            'Transformador: 12v',
            'Control: Caja de control de velocidad',
            'Mando: Joystick',
            'Cable: RCA de 6 mts',
            'Iluminación: LED decorativo en la estructura + 4 barras LED blancas netamente para iluminación',
            'Personalización: Brandeado en la estructura',
            'Disco de pesas: 21 kg',
          ],
          descripcion: 'Cabina 180 Pro — Combo 3. Estructura: 1.20 mt alto x 30 cm ancho.',
          descripcion_larga: 'Cabina 180 Pro — Combo 3. Especificaciones: Estructura: 1.20 mt alto x 30 cm ancho, Brazo: 2.40 mts alto, Soporte: Para celular, Transformador: 12v, Control: Caja de control de velocidad, Mando: Joystick, Cable: RCA de 6 mts, Iluminación: LED decorativo en la estructura + 4 barras LED blancas netamente para iluminación, Personalización: Brandeado en la estructura, Disco de pesas: 21 kg. Costo de este nivel: consultar disponibilidad.',
          imagenes_galeria: ['/imagenes/cabina-180-pro-combo-3-1.jpg', '/imagenes/cabina-180-pro-combo-3-2.jpg', '/imagenes/cabina-180-pro-combo-3-3.jpg', '/imagenes/cabina-180-pro-combo-3-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho' },
            { label: 'Brazo', valor: '2.40 mts alto' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Transformador', valor: '12v' },
            { label: 'Control', valor: 'Caja de control de velocidad' },
            { label: 'Mando', valor: 'Joystick' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Iluminación', valor: 'LED decorativo en la estructura + 4 barras LED blancas netamente para iluminación' },
            { label: 'Personalización', valor: 'Brandeado en la estructura' },
            { label: 'Disco de pesas', valor: '21 kg' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Instalación incluida a nivel nacional', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
        },
      ],
    },
  ],



  // 📊 MÉTRICAS NOSOTROS - DASHBOARD DE AUTORIDAD
  metricas_nosotros: [
    {
      numero: '+10 Años',
      subtitulo: 'Experiencia en el rubro audiovisual peruano',
    },
    {
      numero: '1 Año Garantía',
      subtitulo: 'En todos nuestros equipos',
    },
    {
      numero: '100% Nacional',
      subtitulo: 'Equipos de alta resistencia con soporte inmediato',
    },
  ],

  // 🌐 REDES SOCIALES - ENLACES DINÁMICOS
  redes_sociales: {
    tiktok: 'https://www.tiktok.com/@apicperu',
    instagram: 'https://www.instagram.com/api_cperu',
    facebook: 'https://www.facebook.com/apic2018',
  },

  // 📦 CATÁLOGO GENERAL - TODOS LOS PRODUCTOS COMBINADOS (flujo unificado)
  // Utilizado por app/productos/[id]/page.tsx y app/combos/[id]/page.tsx
  // para la búsqueda de productos sin depender de arreglos separados.
  CATALOGO_GENERAL: [] as any, // Se rellena dinámicamente abajo
}

// Combinar todas las secciones del catálogo en CATALOGO_GENERAL.
// Al ser dinámico sobre 'secciones_catalogo', agregar una nueva sección
// (o productos a una existente) se refleja aquí automáticamente.
WEBSITE_CONFIG.CATALOGO_GENERAL = WEBSITE_CONFIG.secciones_catalogo.flatMap(
  (seccion) => seccion.productos
)