// 🚨 CONFIGURACIÓN ÚNICA CENTRALIZADA - SINGLE SOURCE OF TRUTH (SSOT)
// Este archivo contiene TODA la información del sitio web.
// Los clientes NO técnicos solo deben editar este archivo desde GitHub.
// Todos los cambios aquí se reflejan automáticamente en todas las páginas.
// ¡NO EDITAR CÓDIGO JavaScript abajo! Solo modificar los datos aquí.

// 🎨 TEMA VISUAL - IDENTIDAD CORPORATIVA
export const THEME_CONFIG = {
  color_primario: '#039dbf',
  color_hover: '#02829e',
  color_fondo_tarjetas: '#0080ff',
}

export const WEBSITE_CONFIG = {
  numero_whatsapp: '51994942994',
  numero_whatsapp_m: '51 994 942 994',
  correo_contacto: 'info@apicperu.com',

  temporadas_carrusel: [
    {
      evento_id: 1,
      nombre_evento: 'Presentación Corporativa APIC',
      titulo_carrusel: 'Equipos Audiovisuales y para Eventos de Alto Impacto',
      subtitulo_carrusel: 'Más de 10 años fabricando plataformas 360°, domos, cabinas fotográficas y estructuras para eventos — con garantía de fábrica y envíos a nivel nacional.',
      imagen_carrusel: 'linear-gradient(135deg, #0b0f19 0%, #1f2937 100%)',
      imagen_url: 'https://www.epgdlaw.com/wp-content/uploads/2015/10/89273783_l.jpg',
      nombre_pack: 'Catálogo APIC',
      descripcion_pack: 'Fabricante peruano de soluciones audiovisuales y equipos para eventos, con garantía de fábrica y envíos a nivel nacional.',
      equipos_incluidos: [],
    },
  ],

  // 🗂️ SECCIONES DE CATÁLOGO — ARQUITECTURA POR FAMILIA MADRE
  // Cada bloque de 'secciones_catalogo' representa UNA familia de producto
  // (p. ej. 'Plataforma 360', 'Domos'). Dentro de cada familia, cada nivel
  // Combo N es su PROPIO objeto de producto independiente (id, sku, imagen,
  // descripción, ficha técnica y garantías propias). El Mega Menu y el Home
  // recorren este arreglo dinámicamente: agregar una nueva familia aquí
  // basta para que aparezca automáticamente en ambos.
  secciones_catalogo: [
    {
      id_seccion: 'plataforma-360',
      titulo_seccion: 'Plataforma 360',
      productos: [
        {
          id: 1,
          nombre: 'Plataforma 360 — Combo 1',
          sku: 'P360-EVT-001-C1',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular',
            'Costo: 2200 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 1. Peso: 25 kg. Costo: 2200 soles.',
          descripcion_larga: 'Convierte cualquier celebración en contenido viral: tus invitados suben a la plataforma, extienden los brazos, y la cámara gira 360° capturando cada expresión en un single video que todos querrán compartir.',
          imagenes_galeria: ['/equipos/PLATAFORMA-360º/COMBO 1/PLATAFORMA 360_IMG 1 PLAT 01.jpg', '/equipos/PLATAFORMA-360º/COMBO 1/PLATAFORMA 360_IMG 2 PLAT 01.jpg', '/equipos/PLATAFORMA-360º/COMBO 1/PLATAFORMA 360_IMG 3 PLAT 01.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular' },
            { label: 'Costo', valor: '2200 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },           
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: true,
          precio_antes: 'Precio Antes: 2600 soles',
        },
        {
          id: 2,
          nombre: 'Plataforma 360 — Combo 2',
          sku: 'P360-EVT-001-C2',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado',
            'Costo: 2300 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 2. Peso: 25 kg. Costo: 2300 soles.',
          descripcion_larga: 'La misma magia del giro, ahora con el brillo del aro LED RGB y tu marca personalizada en vinil — cada clip sale listo para redes sociales, con la identidad de tu evento en cada fotograma.',
          imagenes_galeria: ['/equipos/PLATAFORMA-360º/COMBO 2/PLATAFORMA 360_IMG 1 PLAT 02.jpg', '/equipos/PLATAFORMA-360º/COMBO 2/PLATAFORMA 360_IMG 2 PLAT 02.jpg', '/equipos/PLATAFORMA-360º/COMBO 2/PLATAFORMA 360_IMG 3 PLAT 02.jpg', '/equipos/PLATAFORMA-360º/COMBO 2/PLATAFORMA 360_IMG 4 PLAT 02.jpg', '/equipos/PLATAFORMA-360º/COMBO 2/PLATAFORMA 360_IMG 5 PLAT 02.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado' },
            { label: 'Costo', valor: '2300 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 3,
          nombre: 'Plataforma 360 — Combo 3',
          sku: 'P360-EVT-001-C3',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras',
            'Costo: 2500 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 3. Peso: 25 kg. Costo: 2500 soles.',
          descripcion_larga: 'Iluminación profesional de barras LED que elimina cualquier sombra: el resultado luce con calidad de producción audiovisual, no de video casero.',
          imagenes_galeria: ['/equipos/PLATAFORMA-360º/COMBO 3/PLATAFORMA 360_IMG 1 PLAT 03.jpg', '/equipos/PLATAFORMA-360º/COMBO 3/PLATAFORMA 360_IMG 2 PLAT 03.jpg', '/equipos/PLATAFORMA-360º/COMBO 3/PLATAFORMA 360_IMG 3 PLAT 03.jpg', '/equipos/PLATAFORMA-360º/COMBO 3/PLATAFORMA 360_IMG 4 PLAT 03.jpg', '/equipos/PLATAFORMA-360º/COMBO 3/PLATAFORMA 360_IMG 5 PLAT 03.jpg', '/equipos/PLATAFORMA-360º/COMBO 3/PLATAFORMA 360_IMG 6 PLAT 03.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras' },
            { label: 'Costo', valor: '2500 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 4,
          nombre: 'Plataforma 360 — Combo 4',
          sku: 'P360-EVT-001-C4',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja',
            'Costo: 3100 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 4. Peso: 25 kg. Costo: 3100 soles.',
          descripcion_larga: 'Niebla y burbujas convierten cada toma en una escena cinematográfica — el efecto sorpresa está garantizado desde el primer segundo de grabación.',
          imagenes_galeria: ['/equipos/PLATAFORMA-360º/COMBO 4/PLATAFORMA 360_IMG 1 PLAT 04.jpg', '/equipos/PLATAFORMA-360º/COMBO 4/PLATAFORMA 360_IMG 2 PLAT 04.jpg', '/equipos/PLATAFORMA-360º/COMBO 4/PLATAFORMA 360_IMG 3 PLAT 04.jpg', '/equipos/PLATAFORMA-360º/COMBO 4/PLATAFORMA 360_IMG 4 PLAT 04.jpg', '/equipos/PLATAFORMA-360º/COMBO 4/PLATAFORMA 360_IMG 5 PLAT 04-13.jpg', '/equipos/PLATAFORMA-360º/COMBO 4/PLATAFORMA 360_IMG 6 PLAT 04-21.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja' },
            { label: 'Costo', valor: '3100 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 5,
          nombre: 'Plataforma 360 — Combo 5',
          sku: 'P360-EVT-001-C5',
          categoria: 'Plataforma 360',
          especificaciones: [
            'Peso: 25 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja, estuche de lona acolchado de 1 mt, carrito de fierro con 4 ruedas para transportar la plataforma, power bank',
            'Costo: 3600 soles',
          ],
          descripcion: 'Plataforma 360 — Combo 5. Peso: 25 kg. Costo: 3600 soles.',
          descripcion_larga: 'La experiencia completa, lista para viajar: power bank, carrito de transporte y estuche acolchado para que el espectáculo esté listo en cualquier locación, sin depender de un tomacorriente.',
          imagenes_galeria: ['/equipos/PLATAFORMA-360º/COMBO 5/PLATAFORMA 360_IMG 1 PLAT 05.jpg', '/equipos/PLATAFORMA-360º/COMBO 5/PLATAFORMA 360_IMG 2 PLAT 05.jpg', '/equipos/PLATAFORMA-360º/COMBO 5/PLATAFORMA 360_IMG 3 PLAT 05.jpg', '/equipos/PLATAFORMA-360º/COMBO 5/PLATAFORMA 360_IMG 4 PLAT 05.jpg', '/equipos/PLATAFORMA-360º/COMBO 5/PLATAFORMA 360_IMG 5 PLAT 05.jpg', '/equipos/PLATAFORMA-360º/COMBO 5/PLATAFORMA 360_IMG 6 PLAT 05-18.jpg', '/equipos/PLATAFORMA-360º/COMBO 5/PLATAFORMA 360_IMG 6 PLAT 05-22.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '25 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, aro LED RGB, LED decorativa, vinil con el logo de su empresa personalizado, 4 barras LED blancas con enchufe y cable de 2 mts (75w c/u), 4 trípodes para soporte de barras, máquina de humo (control inalámbrico), máquina de burbuja, 500ml de líquido para humo, 500ml de líquido de burbuja, estuche de lona acolchado de 1 mt, carrito de fierro con 4 ruedas para transportar la plataforma, power bank' },
            { label: 'Costo', valor: '3600 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'plataforma-infinito',
      titulo_seccion: 'Plataforma Infinito',
      productos: [
        {
          id: 6,
          nombre: 'Plataforma Infinito — Combo 1',
          sku: 'PINF-EVT-002-C1',
          categoria: 'Plataforma Infinito',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido',
            'Costo: 3050 soles',
          ],
          descripcion: 'Plataforma Infinito — Combo 1. Peso: 35 kg. Costo: 3050 soles.',
          descripcion_larga: 'El piso de vidrio templado añade una dimensión de profundidad que transforma el giro clásico en una experiencia visualmente hipnótica — como flotar en el aire.',
          imagenes_galeria: ['/equipos/INFINITA/COMBO 1/INFINITA_INFINITO COMBO 1 IMG1.jpg', '/equipos/INFINITA/COMBO 1/INFINITA_INFINITO COMBO 1 IMG2.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido' },
            { label: 'Costo', valor: '3050 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 7,
          nombre: 'Plataforma Infinito — Combo 2',
          sku: 'PINF-EVT-002-C2',
          categoria: 'Plataforma Infinito',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación',
            'Costo: 3450 soles',
          ],
          descripcion: 'Plataforma Infinito — Combo 2. Peso: 35 kg. Costo: 3450 soles.',
          descripcion_larga: 'Con iluminación adicional perfectamente distribuida, cada video luce un acabado profesional que hace que los invitados quieran repetir la toma una y otra vez.',
          imagenes_galeria: ['/equipos/INFINITA/COMBO 2/INFINITA_INFINITO COMBO 2 IMG1.jpg', '/equipos/INFINITA/COMBO 2/INFINITA_INFINITO COMBO 2 IMG2.jpg', '/equipos/INFINITA/COMBO 2/INFINITA_INFINITO COMBO 2 IMG3.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación' },
            { label: 'Costo', valor: '3450 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 8,
          nombre: 'Plataforma Infinito — Combo 3',
          sku: 'PINF-EVT-002-C3',
          categoria: 'Plataforma Infinito',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación, máquina de humo, máquina de burbuja',
            'Costo: 3750 soles',
          ],
          descripcion: 'Plataforma Infinito — Combo 3. Peso: 35 kg. Costo: 3750 soles.',
          descripcion_larga: 'La niebla se desliza sobre el vidrio iluminado creando un efecto casi etéreo — el momento más fotografiado de la noche, garantizado.',
          imagenes_galeria: ['/equipos/INFINITA/COMBO 3/INFINITA_INFINITO COMBO 3 IMG1.jpg', '/equipos/INFINITA/COMBO 3/INFINITA_INFINITO COMBO 3 IMG2.jpg', '/equipos/INFINITA/COMBO 3/INFINITA_INFINITO COMBO 3 IMG3.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para LED, 4 barras LED blancas netamente para iluminación, máquina de humo, máquina de burbuja' },
            { label: 'Costo', valor: '3750 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'plataforma-infinito-holograma',
      titulo_seccion: 'Plataforma Infinito Holograma',
      productos: [
        {
          id: 9,
          nombre: 'Plataforma Infinito Holograma — Combo 1',
          sku: 'PINFH-EVT-003-C1',
          categoria: 'Plataforma Infinito Holograma',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido',
            'Costo: 3600 soles',
          ],
          descripcion: 'Plataforma Infinito Holograma — Combo 1. Peso: 35 kg. Costo: 3600 soles.',
          descripcion_larga: 'Un holograma flotante de 40cm eleva el efecto giratorio a otro nivel: no solo se ve, se vive como un pequeño espectáculo de ciencia ficción en medio del evento.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-holograma-combo-1-1.jpg', '/imagenes/plataforma-infinito-holograma-combo-1-2.jpg', '/imagenes/plataforma-infinito-holograma-combo-1-3.jpg', '/imagenes/plataforma-infinito-holograma-combo-1-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido' },
            { label: 'Costo', valor: '3600 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 10,
          nombre: 'Plataforma Infinito Holograma — Combo 2',
          sku: 'PINFH-EVT-003-C2',
          categoria: 'Plataforma Infinito Holograma',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación',
            'Costo: 4000 soles',
          ],
          descripcion: 'Plataforma Infinito Holograma — Combo 2. Peso: 35 kg. Costo: 4000 soles.',
          descripcion_larga: 'Más luz, más presencia: la iluminación adicional envuelve el holograma y el piso de vidrio en un solo momento inolvidable para tus invitados.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-holograma-combo-2-1.jpg', '/imagenes/plataforma-infinito-holograma-combo-2-2.jpg', '/imagenes/plataforma-infinito-holograma-combo-2-3.jpg', '/imagenes/plataforma-infinito-holograma-combo-2-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación' },
            { label: 'Costo', valor: '4000 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 11,
          nombre: 'Plataforma Infinito Holograma — Combo 3',
          sku: 'PINFH-EVT-003-C3',
          categoria: 'Plataforma Infinito Holograma',
          especificaciones: [
            'Peso: 35 kg',
            'Medida: 1 metro de diámetro',
            'Capacidad: 4-5 personas',
            'Color: Negro',
            'Garantía: 1 año',
            'Material: Metal',
            'Vidrio: Templado de 10mm',
            'Características: Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación, máquina de humo, máquina de burbuja',
            'Costo: 4300 soles',
          ],
          descripcion: 'Plataforma Infinito Holograma — Combo 3. Peso: 35 kg. Costo: 4300 soles.',
          descripcion_larga: 'El nivel más alto de nuestro catálogo: holograma, niebla y burbujas trabajando juntos para el cierre de evento más memorable que puedas ofrecer.',
          imagenes_galeria: ['/imagenes/plataforma-infinito-holograma-combo-3-1.jpg', '/imagenes/plataforma-infinito-holograma-combo-3-2.jpg', '/imagenes/plataforma-infinito-holograma-combo-3-3.jpg', '/imagenes/plataforma-infinito-holograma-combo-3-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Peso', valor: '35 kg' },
            { label: 'Medida', valor: '1 metro de diámetro' },
            { label: 'Capacidad', valor: '4-5 personas' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Garantía', valor: '1 año' },
            { label: 'Material', valor: 'Metal' },
            { label: 'Vidrio', valor: 'Templado de 10mm' },
            { label: 'Características', valor: 'Caja de control de velocidad, control inalámbrico de 50 mts de alcance, transformador de 20v, control para holograma, transformador de 12v para holograma, holograma de 40 cm, soporte para celular, power bank, 1 aro LED RGB blanco y cálido, 4 trípodes para iluminación, 4 barras LED netamente blancas para iluminación, máquina de humo, máquina de burbuja' },
            { label: 'Costo', valor: '4300 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'glass-booth',
      titulo_seccion: 'Glass Booth',
      productos: [
        {
          id: 12,
          nombre: 'Glass Booth',
          sku: 'GBTH-EVT-004',
          categoria: 'Glass Booth',
          especificaciones: [
            'Estructura: Desarmable, cuadrada, de 1.22 x 1.22 mt',
            'Altura: 2 metros',
            'Plancha: Negra para branding',
            'Barras: Blancas para iluminación',
            'Forro: Tela negra',
            'Mica: Transparente de 60cm x 1.22cm, efecto espejo de 3mm de espesor',
            'Costo: 1500 soles',
          ],
          descripcion: 'Glass Booth. Estructura: desarmable, cuadrada, de 1.22 x 1.22 mt. Costo: 1500 soles.',
          descripcion_larga: 'Un punto de branding que se convierte en la fotografía más compartida del evento: estructura minimalista y mica espejada, diseñada para que cada invitado se detenga a capturar el momento.',
          imagenes_galeria: ['/equipos/GLASS-BOOTH/INFINITY_GLASS IMG1.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Desarmable, cuadrada, de 1.22 x 1.22 mt' },
            { label: 'Altura', valor: '2 metros' },
            { label: 'Plancha', valor: 'Negra para branding' },
            { label: 'Barras', valor: 'Blancas para iluminación' },
            { label: 'Forro', valor: 'Tela negra' },
            { label: 'Mica', valor: 'Transparente de 60cm x 1.22cm, efecto espejo de 3mm de espesor' },
            { label: 'Costo', valor: '1500 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: true,
          precio_antes: 'Precio Antes: 1800 soles',
        },
      ],
    },
    {
      id_seccion: 'tunel-pixel',
      titulo_seccion: 'Túnel Pixel',
      productos: [
        {
          id: 13,
          nombre: 'Túnel Pixel — Combo 1',
          sku: 'TPIX-EVT-005-C1',
          categoria: 'Túnel Pixel',
          especificaciones: [
            'Estructura: Completamente desarmable',
            'Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad',
            'Material: Acero cuadrado',
            'Color: Negro',
            'Arcos: 6 arcos hexagonales',
            'Costo: 950 soles',
          ],
          descripcion: 'Túnel Pixel — Combo 1. Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad. Costo: 950 soles.',
          descripcion_larga: 'Una entrada que marca el tono del evento desde el primer paso: arcos hexagonales que convierten el simple hecho de caminar en una experiencia memorable.',
          imagenes_galeria: ['/equipos/TUNEL/COMBO 1/TUNEL_TÚNEL COMBO 1 IMG1.jpg', '/equipos/TUNEL/COMBO 1/TUNEL_TÚNEL COMBO 1 IMG2.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Completamente desarmable' },
            { label: 'Medidas', valor: '2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad' },
            { label: 'Material', valor: 'Acero cuadrado' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Arcos', valor: '6 arcos hexagonales' },
            { label: 'Costo', valor: '950 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: true,
          precio_antes: 'Precio Antes: 1200 soles',
        },
        {
          id: 14,
          nombre: 'Túnel Pixel — Combo 2',
          sku: 'TPIX-EVT-005-C2',
          categoria: 'Túnel Pixel',
          especificaciones: [
            'Estructura: Completamente desarmable',
            'Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad',
            'Material: Acero cuadrado',
            'Color: Negro',
            'Arcos: 6 arcos hexagonales',
            'Iluminación: 30 barras pixel con enchufe en cada arco',
            'Costo: 2250 soles',
          ],
          descripcion: 'Túnel Pixel — Combo 2. Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad. Costo: 2250 soles.',
          descripcion_larga: 'Con iluminación pixel en cada arco, el recorrido se vuelve una postal luminosa perfecta para las primeras fotos de la noche.',
          imagenes_galeria: ['/equipos/TUNEL/COMBO 2/TUNEL_TÚNEL COMBO 2 IMG1.jpg', '/equipos/TUNEL/COMBO 2/TUNEL_TÚNEL COMBO 2 IMG2.jpg', '/equipos/TUNEL/COMBO 2/TUNEL_TÚNEL COMBO 2 IMG3.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Completamente desarmable' },
            { label: 'Medidas', valor: '2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad' },
            { label: 'Material', valor: 'Acero cuadrado' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Arcos', valor: '6 arcos hexagonales' },
            { label: 'Iluminación', valor: '30 barras pixel con enchufe en cada arco' },
            { label: 'Costo', valor: '2250 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 15,
          nombre: 'Túnel Pixel — Combo 3',
          sku: 'TPIX-EVT-005-C3',
          categoria: 'Túnel Pixel',
          especificaciones: [
            'Estructura: Completamente desarmable',
            'Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad',
            'Material: Acero cuadrado',
            'Color: Negro',
            'Arcos: 6 arcos hexagonales',
            'Iluminación: 30 barras pixel',
            'Transformadores: 6 transformadores de 12v',
            'Cableado: 5 cables de empalme',
            'Control: 1 controlador rítmico, controlable por app',
            'Costo: 2650 soles',
          ],
          descripcion: 'Túnel Pixel — Combo 3. Medidas: 2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad. Costo: 2650 soles.',
          descripcion_larga: 'Sincronizado al ritmo de la música vía app, el túnel respira con el evento — cada beat se convierte en luz en tiempo real.',
          imagenes_galeria: ['/equipos/TUNEL/COMBO 3/TUNEL_TÚNEL COMBO 3 IMG1.jpg', '/equipos/TUNEL/COMBO 3/TUNEL_TÚNEL COMBO 3 IMG2.jpg', '/equipos/TUNEL/COMBO 3/TUNEL_TÚNEL COMBO 3 IMG3.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Completamente desarmable' },
            { label: 'Medidas', valor: '2.37 mt ancho x 2.10 mt alto x 5 mts de profundidad' },
            { label: 'Material', valor: 'Acero cuadrado' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Arcos', valor: '6 arcos hexagonales' },
            { label: 'Iluminación', valor: '30 barras pixel' },
            { label: 'Transformadores', valor: '6 transformadores de 12v' },
            { label: 'Cableado', valor: '5 cables de empalme' },
            { label: 'Control', valor: '1 controlador rítmico, controlable por app' },
            { label: 'Costo', valor: '2650 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'domos',
      titulo_seccion: 'Domos',
      productos: [
        {
          id: 16,
          nombre: 'Domos — Combo 1',
          sku: 'DOMO-EVT-006-C1',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Básico',
            'Medida armado: 2.25 mt alto x 3.40 mt ancho',
            'Iluminación: 35 barras LED blancas',
            'Piezas: 16 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Precio: 2350 soles',
          ],
          descripcion: 'Domos — Combo 1. Medida armado: 2.25 mt alto x 3.40 mt ancho. Precio: 2350 soles.',
          descripcion_larga: 'Una estructura geodésica que redefine el espacio del evento: elegante, imponente, y lista para convertirse en el punto de encuentro de la noche.',
          imagenes_galeria: ['/equipos/DOMOS/DOMO 1/DOMOS_DOMO COMBO 1 - IMG1.jpg', '/equipos/DOMOS/DOMO 1/DOMOS_DOMO COMBO 1 - IMG2.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Básico' },
            { label: 'Medida armado', valor: '2.25 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '35 barras LED blancas' },
            { label: 'Piezas', valor: '16 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Precio', valor: '2350 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 17,
          nombre: 'Domos — Combo 2',
          sku: 'DOMO-EVT-006-C2',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Premium',
            'Medida armado: 3 mt alto x 3.40 mt ancho',
            'Iluminación: 65 barras LED blancas',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Precio: 3150 soles',
          ],
          descripcion: 'Domos — Combo 2. Medida armado: 3 mt alto x 3.40 mt ancho. Precio: 3150 soles.',
          descripcion_larga: 'Con el doble de iluminación LED, el domo se convierte en un santuario luminoso que envuelve a tus invitados desde el primer momento.',
          imagenes_galeria: ['/equipos/DOMOS/DOMO 2/DOMOS_DOMO COMBO 2 - IMG1.jpg', '/equipos/DOMOS/DOMO 2/DOMOS_DOMO COMBO 2 - IMG2.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Premium' },
            { label: 'Medida armado', valor: '3 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '65 barras LED blancas' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Precio', valor: '3150 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 18,
          nombre: 'Domos — Combo 3',
          sku: 'DOMO-EVT-006-C3',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Premium Pixel',
            'Medida armado: 3 mt alto x 3.40 mt ancho',
            'Iluminación: 65 barras LED blancas + 51 barras pixel',
            'Control: 1 controlador',
            'Transformadores: 5 transformadores de 12v',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Precio: 5199 soles',
          ],
          descripcion: 'Domos — Combo 3. Medida armado: 3 mt alto x 3.40 mt ancho. Precio: 5199 soles.',
          descripcion_larga: 'Barras pixel programables transforman el domo en un lienzo dinámico de luz y color, sincronizado a la energía del evento.',
          imagenes_galeria: ['/equipos/DOMOS/DOMO 3/DOMOS_DOMO COMBO 3 - IMG1.jpg', '/equipos/DOMOS/DOMO 3/DOMOS_DOMO COMBO 3 - IMG2.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Premium Pixel' },
            { label: 'Medida armado', valor: '3 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '65 barras LED blancas + 51 barras pixel' },
            { label: 'Control', valor: '1 controlador' },
            { label: 'Transformadores', valor: '5 transformadores de 12v' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Precio', valor: '5199 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 19,
          nombre: 'Domos — Combo 4',
          sku: 'DOMO-EVT-006-C4',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Aéreo',
            'Medida armado: 3 mt alto x 3.40 mt ancho',
            'Iluminación: 65 barras LED blancas',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Brazo: Extendible',
            'Control: Caja de control de velocidad, inalámbrico',
            'Transformador: 20v',
            'Cable: 6 mts',
            'Soporte: Para celular',
            'Precio: 4350 soles',
          ],
          descripcion: 'Domos — Combo 4. Medida armado: 3 mt alto x 3.40 mt ancho. Precio: 4350 soles.',
          descripcion_larga: 'El brazo extendible añade una perspectiva aérea que documenta el evento como nunca antes se había visto — desde arriba, desde adentro del domo.',
          imagenes_galeria: ['/equipos/DOMOS/DOMO 4/DOMOS_DOMO COMBO 4 - IMG1.jpg', '/equipos/DOMOS/DOMO 4/DOMOS_DOMO COMBO 4 - IMG2.jpg', '/equipos/DOMOS/DOMO 4/DOMOS_DOMO COMBO 4 - IMG3.jpg', '/equipos/DOMOS/DOMO 4/DOMOS_DOMO COMBO 4 - IMG4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Aéreo' },
            { label: 'Medida armado', valor: '3 mt alto x 3.40 mt ancho' },
            { label: 'Iluminación', valor: '65 barras LED blancas' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Brazo', valor: 'Extendible' },
            { label: 'Control', valor: 'Caja de control de velocidad, inalámbrico' },
            { label: 'Transformador', valor: '20v' },
            { label: 'Cable', valor: '6 mts' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Precio', valor: '4350 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 20,
          nombre: 'Domos — Combo 5',
          sku: 'DOMO-EVT-006-C5',
          categoria: 'Domos',
          especificaciones: [
            'Variante: Domo Aéreo Premium Pixel',
            'Iluminación: 65 barras LED blancas + 51 barras pixel',
            'Piezas: 21 piezas',
            'Cableado: Incluido con empalmes',
            'Material: Metal, fierro, tubo cuadrado',
            'Brazo: Extendible',
            'Control: Caja de control de velocidad, inalámbrico, 1 controlador para pixel',
            'Transformadores: 20v (brazo) + 5 transformadores de 12v (pixel)',
            'Cable: RCA de 6 mts',
            'Soporte: Para celular',
            'Precio: 6550 soles',
          ],
          descripcion: 'Domos — Combo 5. Precio: 6550 soles.',
          descripcion_larga: 'La versión definitiva: altura, luz programable y captura aérea trabajando en conjunto para el montaje más ambicioso de nuestro catálogo.',
          imagenes_galeria: ['/equipos/DOMOS/DOMO 5/DOMOS_DOMO COMBO 5 - IMG1.jpg', '/equipos/DOMOS/DOMO 5/DOMOS_DOMO COMBO 5 - IMG2.jpg', '/equipos/DOMOS/DOMO 5/DOMOS_DOMO COMBO 5 - IMG3.jpg', '/equipos/DOMOS/DOMO 5/DOMOS_DOMO COMBO 5 - IMG4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Variante', valor: 'Domo Aéreo Premium Pixel' },
            { label: 'Iluminación', valor: '65 barras LED blancas + 51 barras pixel' },
            { label: 'Piezas', valor: '21 piezas' },
            { label: 'Cableado', valor: 'Incluido con empalmes' },
            { label: 'Material', valor: 'Metal, fierro, tubo cuadrado' },
            { label: 'Brazo', valor: 'Extendible' },
            { label: 'Control', valor: 'Caja de control de velocidad, inalámbrico, 1 controlador para pixel' },
            { label: 'Transformadores', valor: '20v (brazo) + 5 transformadores de 12v (pixel)' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Precio', valor: '6550 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'foto-cabina',
      titulo_seccion: 'Foto Cabina',
      productos: [
        {
          id: 21,
          nombre: 'Foto Cabina — Combo 1',
          sku: 'FCAB-EVT-007-C1',
          categoria: 'Foto Cabina',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad',
            'Mesa: Para impresora, 40x40 cm',
            'Tambor: 45 cm',
            'Aro LED: 45 cm',
            'Controles: 1 control para LED RGB, 1 control para el aro LED',
            'Transformadores: 2 transformadores de 12v',
            'Vinil: Personalizado — foto cabina, mesa y tambor',
            'Soporte: Para iPad',
            'Costo: 2100 soles',
          ],
          descripcion: 'Foto Cabina — Combo 1. Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad. Costo: 2100 soles.',
          descripcion_larga: 'Recuerdos físicos en segundos: cada invitado se lleva una fotografía impresa al instante, personalizada con la identidad de tu marca o evento.',
          imagenes_galeria: ['/equipos/FOTOCABINA/COMBO 1/FOTOCABINA_FOTO COMBO 1 IMG1.jpg', '/equipos/FOTOCABINA/COMBO 1/FOTOCABINA_FOTO COMBO 1 IMG2.jpg', '/equipos/FOTOCABINA/COMBO 1/FOTOCABINA_FOTO COMBO 1 IMG3.jpg', '/equipos/FOTOCABINA/COMBO 1/FOTOCABINA_FOTO COMBO 1 IMG4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho x 15 cm profundidad' },
            { label: 'Mesa', valor: 'Para impresora, 40x40 cm' },
            { label: 'Tambor', valor: '45 cm' },
            { label: 'Aro LED', valor: '45 cm' },
            { label: 'Controles', valor: '1 control para LED RGB, 1 control para el aro LED' },
            { label: 'Transformadores', valor: '2 transformadores de 12v' },
            { label: 'Vinil', valor: 'Personalizado — foto cabina, mesa y tambor' },
            { label: 'Soporte', valor: 'Para iPad' },
            { label: 'Costo', valor: '2100 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: true,
          precio_antes: 'Precio Antes: 2500 soles',
        },
        {
          id: 22,
          nombre: 'Foto Cabina — Combo 2',
          sku: 'FCAB-EVT-007-C2',
          categoria: 'Foto Cabina',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad',
            'Mesa: Para impresora, 40x40 cm',
            'Tambor: 45 cm',
            'Aro LED: 45 cm',
            'Controles: 1 control para LED RGB, 1 control para el aro LED',
            'Transformadores: 2 transformadores de 12v',
            'Vinil: Personalizado — foto cabina, mesa y tambor',
            'Soporte: Para iPad',
            'Accesorios adicionales: Guillotina incluida',
            'Impresora: Epson L1250 WiFi',
            'Costo: 3500 soles',
          ],
          descripcion: 'Foto Cabina — Combo 2. Estructura: 1.20 mt alto x 30 cm ancho x 15 cm profundidad. Costo: 3500 soles.',
          descripcion_larga: 'Con impresora profesional Epson WiFi y corte automático, el flujo de impresión es tan rápido como la fila de invitados esperando su turno.',
          imagenes_galeria: ['/equipos/FOTOCABINA/COMBO 2/FOTOCABINA_FOTO COMBO 2 IMG1-05.jpg', '/equipos/FOTOCABINA/COMBO 2/FOTOCABINA_FOTO COMBO 2 IMG1-06.jpg', '/equipos/FOTOCABINA/COMBO 2/FOTOCABINA_FOTO COMBO 2 IMG1-07.jpg', '/equipos/FOTOCABINA/COMBO 2/FOTOCABINA_FOTO COMBO 2 IMG1-08.jpg', '/equipos/FOTOCABINA/COMBO 2/FOTOCABINA_FOTO COMBO 2 IMG1-09.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho x 15 cm profundidad' },
            { label: 'Mesa', valor: 'Para impresora, 40x40 cm' },
            { label: 'Tambor', valor: '45 cm' },
            { label: 'Aro LED', valor: '45 cm' },
            { label: 'Controles', valor: '1 control para LED RGB, 1 control para el aro LED' },
            { label: 'Transformadores', valor: '2 transformadores de 12v' },
            { label: 'Vinil', valor: 'Personalizado — foto cabina, mesa y tambor' },
            { label: 'Soporte', valor: 'Para iPad' },
            { label: 'Accesorios adicionales', valor: 'Guillotina incluida' },
            { label: 'Impresora', valor: 'Epson L1250 WiFi' },
            { label: 'Costo', valor: '3500 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'aereo-360',
      titulo_seccion: 'Aéreo 360',
      productos: [
        {
          id: 23,
          nombre: 'Aéreo 360',
          sku: 'A360-EVT-008',
          categoria: 'Aéreo 360',
          especificaciones: [
            'Estructura: Desarmable en 6 piezas',
            'Medidas: 2.40 mt alto x 3 mts ancho',
            'Forro: Color negro',
            'Brazo: Regulable',
            'Control: Caja de control de velocidad, inalámbrico',
            'Transformador: 20v',
            'Soporte: Para celular',
            'Costo: 3200 soles',
          ],
          descripcion: 'Aéreo 360. Medidas: 2.40 mt alto x 3 mts ancho. Costo: 3200 soles.',
          descripcion_larga: 'Perspectiva elevada, impacto garantizado: el brazo regulable capta ángulos que ninguna cámara de mano puede lograr, dando a cada video un acabado de producción profesional.',
          imagenes_galeria: ['/equipos/AÉREO-360º/INFINITY_AÉREO 360 IMG1.jpg', '/equipos/AÉREO-360º/INFINITY_AÉREO 360 IMG2.jpg', '/equipos/AÉREO-360º/INFINITY_AÉREO 360 IMG3.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: 'Desarmable en 6 piezas' },
            { label: 'Medidas', valor: '2.40 mt alto x 3 mts ancho' },
            { label: 'Forro', valor: 'Color negro' },
            { label: 'Brazo', valor: 'Regulable' },
            { label: 'Control', valor: 'Caja de control de velocidad, inalámbrico' },
            { label: 'Transformador', valor: '20v' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Costo', valor: '3200 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'balaustres',
      titulo_seccion: 'Balaustres',
      productos: [
        {
          id: 24,
          nombre: 'Balaustres',
          sku: 'BALU-EVT-009',
          categoria: 'Balaustres',
          especificaciones: [
            'Balaustre: Color dorado, 1 mt',
            'Cordón: Color rojo, 1.50 mts',
            'Disco: De pesa, para base',
            'Estructura: Desarmable, 6 piezas',
            'Costo: 210 soles',
          ],
          descripcion: 'Balaustres. Estructura: desarmable, 6 piezas. Costo: 210 soles.',
          descripcion_larga: 'El detalle que distingue un evento premium de uno común: cordón rojo y acabado dorado que delimitan con elegancia cualquier acceso VIP o alfombra roja.',
          imagenes_galeria: ['/imagenes/balaustres-1.jpg', '/imagenes/balaustres-2.jpg', '/imagenes/balaustres-3.jpg', '/imagenes/balaustres-4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Balaustre', valor: 'Color dorado, 1 mt' },
            { label: 'Cordón', valor: 'Color rojo, 1.50 mts' },
            { label: 'Disco', valor: 'De pesa, para base' },
            { label: 'Estructura', valor: 'Desarmable, 6 piezas' },
            { label: 'Costo', valor: '210 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: true,
          precio_antes: 'Precio Antes: 250 soles',
        },
      ],
    },
    {
      id_seccion: 'cabina-espejada',
      titulo_seccion: 'Cabina Espejada',
      productos: [
        {
          id: 25,
          nombre: 'Cabina Espejada — Combo 1',
          sku: 'CESP-EVT-010-C1',
          categoria: 'Cabina Espejada',
          especificaciones: [
            'Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad',
            'Material: Tubo cuadrado, acero y fierro',
            'Color: Negro',
            'Costo: 650 soles',
          ],
          descripcion: 'Cabina Espejada — Combo 1. Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad. Costo: 650 soles.',
          descripcion_larga: 'Una silueta minimalista en acero que se adapta con versatilidad a cualquier ambientación de marca o temática de evento.',
          imagenes_galeria: ['/equipos/CABINA-ESPEJADA/COMBO 1/CABINA ESPEJADA_CABINA ESP COMBO 1 IMG1.jpg', '/equipos/CABINA-ESPEJADA/COMBO 1/CABINA ESPEJADA_CABINA ESP COMBO 1 IMG2.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Medidas', valor: '2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad' },
            { label: 'Material', valor: 'Tubo cuadrado, acero y fierro' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Costo', valor: '650 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: true,
          precio_antes: 'Precio Antes: 850 soles',
        },
        {
          id: 26,
          nombre: 'Cabina Espejada — Combo 2',
          sku: 'CESP-EVT-010-C2',
          categoria: 'Cabina Espejada',
          especificaciones: [
            'Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad',
            'Material: Tubo cuadrado, acero y fierro',
            'Color: Negro',
            'Acabado: 6 planchas tipo espejo plateado de 8mm de espesor',
            'Ensamblaje: Con pernos',
            'Precio: 2250 soles',
          ],
          descripcion: 'Cabina Espejada — Combo 2. Medidas: 2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad. Precio: 2250 soles.',
          descripcion_larga: 'Recubierta en planchas espejadas, la cabina se convierte en una instalación envolvente: cada ángulo refleja luz, color y a los propios invitados, creando el rincón fotográfico más buscado del evento.',
          imagenes_galeria: ['/equipos/CABINA-ESPEJADA/COMBO 2/CABINA ESPEJADA_CABINA ESP COMBO 2 IMG1.jpg', '/equipos/CABINA-ESPEJADA/COMBO 2/CABINA ESPEJADA_CABINA ESP COMBO 2 IMG2.jpg', '/equipos/CABINA-ESPEJADA/COMBO 2/CABINA ESPEJADA_CABINA ESP COMBO 2 IMG3.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Medidas', valor: '2.20 mt alto x 2.44 mt ancho x 1.22 mt profundidad' },
            { label: 'Material', valor: 'Tubo cuadrado, acero y fierro' },
            { label: 'Color', valor: 'Negro' },
            { label: 'Acabado', valor: '6 planchas tipo espejo plateado de 8mm de espesor' },
            { label: 'Ensamblaje', valor: 'Con pernos' },
            { label: 'Precio', valor: '2250 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
    {
      id_seccion: 'cabina-180-pro',
      titulo_seccion: 'Cabina 180 Pro',
      productos: [
        {
          id: 27,
          nombre: 'Cabina 180 Pro — Combo 1',
          sku: 'C180-EVT-011-C1',
          categoria: 'Cabina 180 Pro',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho',
            'Brazo: 2.40 mts alto',
            'Soporte: Para celular',
            'Transformador: 12v',
            'Control: Caja de control de velocidad',
            'Mando: Joystick',
            'Cable: RCA de 6 mts',
            'Costo: 2900 soles',
          ],
          descripcion: 'Cabina 180 Pro — Combo 1. Estructura: 1.20 mt alto x 30 cm ancho. Costo: 2900 soles.',
          descripcion_larga: 'Video panorámico en 180°, controlado con precisión de joystick: cada toma se siente coreografiada, como si un director estuviera detrás de cámara.',
          imagenes_galeria: ['/equipos/CABINA-180º/COMBO 1/CABINA 180_CABINA 180 COMBO 1 - IMG1.jpg', '/equipos/CABINA-180º/COMBO 1/CABINA 180_CABINA 180 COMBO 1 - IMG2.jpg', '/equipos/CABINA-180º/COMBO 1/CABINA 180_CABINA 180 COMBO 1 - IMG3.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho' },
            { label: 'Brazo', valor: '2.40 mts alto' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Transformador', valor: '12v' },
            { label: 'Control', valor: 'Caja de control de velocidad' },
            { label: 'Mando', valor: 'Joystick' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Costo', valor: '2900 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 28,
          nombre: 'Cabina 180 Pro — Combo 2',
          sku: 'C180-EVT-011-C2',
          categoria: 'Cabina 180 Pro',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho',
            'Brazo: 2.40 mts alto',
            'Soporte: Para celular',
            'Transformador: 12v',
            'Control: Caja de control de velocidad',
            'Mando: Joystick',
            'Cable: RCA de 6 mts',
            'Iluminación: LED decorativo en la estructura',
            'Personalización: Brandeado en la estructura',
            'Costo: 3050 soles',
          ],
          descripcion: 'Cabina 180 Pro — Combo 2. Estructura: 1.20 mt alto x 30 cm ancho. Costo: 3050 soles.',
          descripcion_larga: 'Con iluminación LED decorativa y tu marca integrada en la estructura, el resultado se siente tan cuidado como una producción de estudio.',
          imagenes_galeria: ['/equipos/CABINA-180º/COMBO 2/CABINA 180_CABINA 180 COMBO 2 - IMG1.jpg', '/equipos/CABINA-180º/COMBO 2/CABINA 180_CABINA 180 COMBO 2 - IMG2.jpg', '/equipos/CABINA-180º/COMBO 2/CABINA 180_CABINA 180 COMBO 2 - IMG3.jpg', '/equipos/CABINA-180º/COMBO 2/CABINA 180_CABINA 180 COMBO 2 - IMG4.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho' },
            { label: 'Brazo', valor: '2.40 mts alto' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Transformador', valor: '12v' },
            { label: 'Control', valor: 'Caja de control de velocidad' },
            { label: 'Mando', valor: 'Joystick' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Iluminación', valor: 'LED decorativo en la estructura' },
            { label: 'Personalización', valor: 'Brandeado en la estructura' },
            { label: 'Costo', valor: '3050 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
        {
          id: 29,
          nombre: 'Cabina 180 Pro — Combo 3',
          sku: 'C180-EVT-011-C3',
          categoria: 'Cabina 180 Pro',
          especificaciones: [
            'Estructura: 1.20 mt alto x 30 cm ancho',
            'Brazo: 2.40 mts alto',
            'Soporte: Para celular',
            'Transformador: 12v',
            'Control: Caja de control de velocidad',
            'Mando: Joystick',
            'Cable: RCA de 6 mts',
            'Iluminación: LED decorativo en la estructura + 4 barras LED blancas netamente para iluminación',
            'Personalización: Brandeado en la estructura',
            'Disco de pesas: 21 kg',
            'Costo: 3200 soles',
          ],
          descripcion: 'Cabina 180 Pro — Combo 3. Estructura: 1.20 mt alto x 30 cm ancho. Costo: 3200 soles.',
          descripcion_larga: 'La configuración más robusta de la familia: iluminación adicional y mayor estabilidad para tomas impecables incluso en los eventos más exigentes.',
          imagenes_galeria: ['/equipos/CABINA-180º/COMBO 3/CABINA 180_CABINA 180 COMBO 3 - IMG1.jpg', '/equipos/CABINA-180º/COMBO 3/CABINA 180_CABINA 180 COMBO 3 - IMG2.jpg', '/equipos/CABINA-180º/COMBO 3/CABINA 180_CABINA 180 COMBO 3 - IMG3.jpg', '/equipos/CABINA-180º/COMBO 3/CABINA 180_CABINA 180 COMBO 3 - IMG4.jpg', '/equipos/CABINA-180º/COMBO 3/CABINA 180_CABINA 180 COMBO 3 - IMG5.jpg'],
          sobre_la_marca: 'APIC es fabricante líder en soluciones audiovisuales con más de 10 años de experiencia en eventos de alto impacto.',
          ficha_tecnica: [
            { label: 'Estructura', valor: '1.20 mt alto x 30 cm ancho' },
            { label: 'Brazo', valor: '2.40 mts alto' },
            { label: 'Soporte', valor: 'Para celular' },
            { label: 'Transformador', valor: '12v' },
            { label: 'Control', valor: 'Caja de control de velocidad' },
            { label: 'Mando', valor: 'Joystick' },
            { label: 'Cable', valor: 'RCA de 6 mts' },
            { label: 'Iluminación', valor: 'LED decorativo en la estructura + 4 barras LED blancas netamente para iluminación' },
            { label: 'Personalización', valor: 'Brandeado en la estructura' },
            { label: 'Disco de pesas', valor: '21 kg' },
            { label: 'Costo', valor: '3200 soles' },
          ],
          garantias: [
            { pregunta: 'Garantía de fábrica APIC (1 año)', respuesta: 'SÍ' },
            { pregunta: 'Cobertura por defectos de fabricación', respuesta: 'SÍ' },
            { pregunta: 'Reemplazo por daño de uso indebido', respuesta: 'NO' },
          ],
          en_oferta: false,
          precio_antes: null,
        },
      ],
    },
  ],



  // 📊 MÉTRICAS NOSOTROS - DASHBOARD DE AUTORIDAD
  metricas_nosotros: [
    {
      numero: '+10 Años',
      subtitulo: 'Experiencia en el rubro audiovisual peruano',
    },
    {
      numero: '1 Año Garantía',
      subtitulo: 'En todos nuestros equipos',
    },
    {
      numero: '100% Nacional',
      subtitulo: 'Equipos de alta resistencia con soporte inmediato',
    },
  ],

  // 🌐 REDES SOCIALES - ENLACES DINÁMICOS
  redes_sociales: {
    tiktok: 'https://www.tiktok.com/@apicperu',
    instagram: 'https://www.instagram.com/api_cperu',
    facebook: 'https://www.facebook.com/apic2018',
  },

  // 📦 CATÁLOGO GENERAL - TODOS LOS PRODUCTOS COMBINADOS (flujo unificado)
  // Utilizado por app/productos/[id]/page.tsx y app/combos/[id]/page.tsx
  // para la búsqueda de productos sin depender de arreglos separados.
  CATALOGO_GENERAL: [] as any, // Se rellena dinámicamente abajo
}

// Combinar todas las secciones del catálogo en CATALOGO_GENERAL.
// Al ser dinámico sobre 'secciones_catalogo', agregar una nueva sección
// (o productos a una existente) se refleja aquí automáticamente.
WEBSITE_CONFIG.CATALOGO_GENERAL = WEBSITE_CONFIG.secciones_catalogo.flatMap(
  (seccion) => seccion.productos
)